# Generated by Django 3.0.3 on 2020-05-19 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alimentador',
            fields=[
                ('id', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=256)),
                ('link', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=256)),
                ('link', models.CharField(max_length=256)),
                ('selected', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('cuerpo', models.TextField()),
                ('fecha', models.DateTimeField(verbose_name='publicado')),
                ('contenido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miscosas.Item')),
            ],
        ),
    ]
