# Generated by Django 3.0.3 on 2020-05-21 11:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('miscosas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentario',
            old_name='contenido',
            new_name='item',
        ),
        migrations.RemoveField(
            model_name='item',
            name='selected',
        ),
        migrations.AddField(
            model_name='item',
            name='alimentador',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='miscosas.Alimentador'),
            preserve_default=False,
        ),
    ]
