# Generated by Django 3.0.3 on 2020-05-21 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miscosas', '0002_auto_20200521_1126'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alimentador',
            old_name='title',
            new_name='name',
        ),
    ]
