# Generated by Django 3.0.3 on 2020-05-24 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miscosas', '0004_item_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alimentador',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='item',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
