# Generated by Django 3.0.3 on 2020-05-26 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miscosas', '0008_item_selected'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alimentador',
            name='id',
            field=models.CharField(max_length=256, primary_key=True, serialize=False),
        ),
    ]
