# Generated by Django 3.0.3 on 2020-05-28 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miscosas', '0011_auto_20200528_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alimentador',
            name='link',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='item',
            name='link',
            field=models.CharField(max_length=256),
        ),
    ]
