# Generated by Django 3.0.3 on 2020-05-30 12:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('miscosas', '0012_auto_20200528_1554'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='selected',
        ),
        migrations.AddField(
            model_name='alimentador',
            name='selected',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='comentario',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
