# Generated by Django 3.0.3 on 2020-05-30 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miscosas', '0013_auto_20200530_1231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentario',
            name='user',
        ),
    ]
