# Generated by Django 3.0.3 on 2020-05-30 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miscosas', '0014_remove_comentario_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comentario',
        ),
    ]
