# Generated by Django 3.0.3 on 2020-06-01 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miscosas', '0017_vote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilephoto',
            name='foto_perfil',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
    ]
