# Generated by Django 3.0.3 on 2020-06-03 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miscosas', '0019_auto_20200603_1637'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='puntuacion',
        ),
    ]
