# Generated by Django 3.0.3 on 2020-06-03 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miscosas', '0020_remove_item_puntuacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='puntuacion',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='votos_negativos',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='votos_positivos',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
