# Generated by Django 3.0.3 on 2020-06-03 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miscosas', '0021_auto_20200603_1659'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentario',
            name='titulo',
        ),
    ]
