# Generated by Django 3.0.3 on 2020-06-12 15:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('miscosas', '0023_auto_20200604_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='votado'),
            preserve_default=False,
        ),
    ]
