# Generated by Django 3.0.3 on 2020-04-06 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acortar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenido',
            name='valor',
            field=models.CharField(max_length=64),
        ),
    ]
