# Generated by Django 3.0.3 on 2020-04-06 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acortar', '0003_auto_20200406_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenido',
            name='valor',
            field=models.CharField(max_length=64),
        ),
    ]
