# Generated by Django 3.0.3 on 2020-04-06 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acortar', '0004_auto_20200406_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenido',
            name='clave',
            field=models.IntegerField(),
        ),
    ]
