# Generated by Django 3.0.3 on 2020-04-06 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acortar', '0005_auto_20200406_1635'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contenido',
            name='clave',
        ),
    ]
