# Generated by Django 3.0.3 on 2020-04-09 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acortar', '0006_remove_contenido_clave'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contenido',
            old_name='valor',
            new_name='clave',
        ),
    ]
